language: java
jdk:
  - oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: e/nz2OOgnEmf8JaaLT7To4oBMEtZ3WGaMR2z013LSWS9ttyCVU8ECjfCkek932nMaSbIGXbMFsJRqexgSUIgRiDjlTDmJhXu/gG4sMhEa2YWLn4UTs+rPJPucy4X/7/Tg+KdWShnFg93Cfod7+QDFV7GDikeLCXjeXXIw+KX9T4zy2yXGUwtdux1Ng/15q6iUi0f+FwCiyk77eOtFqxN8yA3zbKsH5kNTfVWFQSfkU+bfZ5tD/HqHvxdlqxDti8xo1t0RFzSoXBGUczMCgYQu8zoeRd+Os9w1rRUXGBdHnp4e5qtBgIZut49/YI6EWwiF5oRwS/M87aX1DD/SAA4TYizB8vlccbaGI16BoO02JVlfnh6nM4QCUr6OZXoXjOxxVbAnSygaj+V2j1rJy5q3u817lr9WMDs4tNdYu2HZV4aJbgkWmQyTRfA6GCd+wOIJgFCmOr1LWjPocL+jU++V0qBsXLSqOFSzaYlJXhxpv9C9GOcU1Ve1tNmqLFc/E4b3EZHBNkAvxj30uDFl/6nNpJwDSDaxE06cFWS+9T9p8HEq/5PL+Bl9+y7h62l3bEQiMg5h2JtU7hcGUaVsyw6pRlEUSItqXtTYdfG0S74FlPFUfzgOPTt2bW5f83c6dJeW/u0i59BLTe/qrtcRVv1xKXRc/3YL3NWVKZ+f9RF1bY=
  app: basic-cicd
